name: Deploy to vercel
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: npx now deploy --token ${{ secrets.VERCEL_TOKEN }} --name ontario-covid-tracker
