name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  deploy to vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build
      - run: npx now deploy --token ${{ secrets.VERCEL_TOKEN }} --name ontario-covid-tracker
