name: production-release
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - name: npm run build
        run: npm run build
        env:
          serviceName: "covid-search"
          indexName: "ca-ontario-index"
          apiKey: ${{ secrets.SEARCH_QUERY_KEY }}
          apiVersion: "2019-05-06"

      - run: npx now --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}
