name: production-release
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.2
      - run: npm ci
      - name: deploy via now
        run: npx now --build-env serviceName=covid-search --build-env indexName=ca-ontario-index --build-env apiKey=${{ secrets.SEARCH_QUERY_KEY }} --build-env apiVersion=2019-05-06 --prod --confirm --token ${{ secrets.VERCEL_TOKEN }}
